### PR TITLE
fix: properly clone error instances

### LINKED ISSUE #611: The logger strips important error information when errors are passed as properties
When we clone the log data (in order to stop original objects being modified) the library we're using strips important error information. This means that our recent feature (allowing error objects to be passed in as properties) is broken.

Thanks @metart43 for spotting this!

**Node.js version:** All
**Impacted package(s):** Logger

## Steps to reproduce

I wrote a test case (see PR #610) to illustrate the problem. If you want to reproduce the issue:

```js
const { OperationalError } = require('@dotcom-reliability-kit/errors');
const logger = require('@dotcom-reliability-kit/logger');

// Works as expected, logs {error: { name: 'OperationalError', code: 'code1', message: 'msg1', ... }}
logger.info(new OperationalError({
    code: 'code1',
    message: 'msg1'
}));

// Strips information, logs {error: { name: 'Error', code: 'UNKNOWN', message: 'msg2', ... }}
logger.info({
    error: new OperationalError({
        code: 'code2',
        message: 'msg2'
    })
})
```

## Expected behaviour

The error should be logged with all details (`name`, `code`, etc). I have a pretty strong suspicion that this just won't work with the current cloning library, perhaps it won't work with any cloning library. We maybe need to assess whether it's that important to not modify the original log object.

### PR DESCRIPTION
**Pull request by rowanmanning**
This switches out the library we use for cloning objects because the original one did not properly handle error objects, which resulted in a loss of log data. This works with Lodash as indicated by the now-passing test - we should now not lose error info.

This fixes an issue Artem was having when trying to use the `error` property of log data:

```js
logger.error({
    error: new Error('...')
})
```

Resolves #611. Closes #610.

### CODE REVIEW

File: packages/logger/lib/logger.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 const pino = require('pino').default;
 const serializeError = require('@dotcom-reliability-kit/serialize-error');
-const { default: clone } = require('@ungap/structured-clone');
+const clone = require('lodash.clonedeep');
```
Comment (metart43) [inline packages/logger/lib/logger.js:3]: Sorry for being annoying, but I'd require `cloneDeep`. It seems like lodash has a separate method called `clone`

```suggestion
const cloneDeep = require('lodash.clonedeep');
```

**Comment by metart43** [comment]
Thanks for resolving this @rowanmanning !

File: packages/logger/lib/logger.js (hunk 1 above)
Comment (rowanmanning) [reply packages/logger/lib/logger.js:3]: I think I'm OK with it staying as-is, as it results in an easier-to-read diff and the library we use to clone is kind of an implementation detail. We don't install lodash.clone so don't think that'd cause confusion, and we also didn't use the name `structuredClone` when we were using that library

**Review by metart43 — APPROVED** [review]

**Review by CyntiBinti — APPROVED** [review]
🎉
